### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by tstibbs** [big-data-europe/docker-hbase#10]
What's the status of this repo? It hasn't been updated for over two years. Googling suggests that the BDE project has ended, suggesting there are unlikely to be any further updates. However the [docker-hadoop](https://github.com/big-data-europe/docker-hadoop) repo gets updated fairly frequently (by @eagafonov most recently), suggesting that perhaps there is a little activity in this area.

I could easily submit a PR to bump the version of hbase, but I'm not clear if there are any contributors likely to merge the PR and then not sure if that's actually going to result in a new image being pushed  to the docker hub?

**Comment by earthquakesan** [comment]
@tstibbs hi! thanks for the interest, this whole org was a part of EU project Big Data Europe 2020, which was over two years ago. There are still people using parts of it (mostly hadoop and spark). HBase simply does not have enough interest. If you will have PR, me or @GezimSejdiu can merge.
